name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Set this to your branch name (e.g. main or master)

jobs:
  web-deploy:
    name: Sync Files via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4

      - name: Sync Files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/